name: "CI: Linting Dockerfile"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      -
        name: Hadolint
        if: github.event_name != 'pull_request'
        uses: brpaz/hadolint-action@c27bd9edc1e95eed30474db8f295ff5807ebca14 # v1.5.0
        with: 
          dockerfile: Dockerfile
      -
        name: Hadolint for PR
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-hadolint@d76e28404b1d5fc19bfaa1f1d9a97dbfffe47032 # v1.50.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true